apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "jaeger.odd.works"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-all-in-one
            port:
              number: 4318

