apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sfs-jaeger
  annotations:
    everest.io/disk-volume-type: SAS
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-disk
