apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loadtest-app
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 5
        type: Pods
        value: 1
      selectPolicy: Min
      stabilizationWindowSeconds: 0
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 7
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtest-app
